name: MkDocs Build
run-name: MkDocs Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build with MkDocs
      uses: Tiryoh/actions-mkdocs@v0
    # - name: Upload artifact
    #   uses: actions/upload-pages-artifact@v1.0.9
  # 
  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Configure Pages
  #     uses: actions/configure-pages@v4.0.0
  #   - name: Deploy to Pages
  #     uses: actions/deploy-pages@v3.0.1
